{
 "title": "CrowdSec Firewall Bouncer",
 "tags": [
  "security",
  "crowdsec",
  "firewall"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(fw_bouncer_banned_ips,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Instant Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Banned IPs",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fw_bouncer_banned_ips{instance=\"$instance\"}",
     "legendFormat": "{{origin}}"
    }
   ]
  },
  {
   "title": "Dropped Packets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fw_bouncer_dropped_packets{instance=\"$instance\"}",
     "legendFormat": "{{origin}}"
    }
   ]
  },
  {
   "title": "Dropped Bytes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fw_bouncer_dropped_bytes{instance=\"$instance\"}",
     "legendFormat": "{{origin}}"
    }
   ]
  },
  { "title": "Stats over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Banned IPs",
   "type": "timeseries",
   "description": "Banned IPs over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "fw_bouncer_banned_ips{instance=\"$instance\"}",
     "legendFormat": "{{ origin }}"
    }
   ]
  },
  {
   "title": "Dropped Packets",
   "type": "timeseries",
   "description": "Amount of dropped packets in percent",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(fw_bouncer_dropped_packets{instance=\"$instance\"}) / sum(fw_bouncer_processed_packets{instance=\"$instance\"}) * 100",
     "legendFormat": "Dropped"
    }
   ]
  }
 ]
}