## This configuration was generated by terraform-provider-oci

resource oci_core_subnet export_subnet-20250216-1019 {
  cidr_block     = "10.0.0.0/24"
  compartment_id = data.bitwarden_secret.tenancy_ocid.value
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ganeshbhambarkar@gmail.com"
    "Oracle-Tags.CreatedOn" = "2025-02-16T09:30:25.142Z"
  }
  dhcp_options_id = oci_core_vcn.default-vcn.default_dhcp_options_id
  display_name    = "gateway-subnet"
  dns_label       = "subnet02161030"
  freeform_tags = {
  }
  prohibit_internet_ingress  = "false"
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_vcn.default-vcn.default_route_table_id
  security_list_ids = [
    oci_core_vcn.default-vcn.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.default-vcn.id
}

resource oci_core_vcn default-vcn {
  cidr_blocks = [
    "10.0.0.0/16",
  ]
  compartment_id = data.bitwarden_secret.tenancy_ocid.value
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ganeshbhambarkar@gmail.com"
    "Oracle-Tags.CreatedOn" = "2025-02-16T09:30:18.782Z"
  }
  display_name = "default-vcn"
  dns_label    = "vcn02161030"
  freeform_tags = {
  }
  ipv6private_cidr_blocks = [
  ]
  security_attributes = {
  }
}

resource oci_core_internet_gateway export_Internet-Gateway-default-vcn {
  compartment_id = data.bitwarden_secret.tenancy_ocid.value
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ganeshbhambarkar@gmail.com"
    "Oracle-Tags.CreatedOn" = "2025-02-16T09:30:20.870Z"
  }
  display_name = "Internet Gateway default-vcn"
  enabled      = "true"
  freeform_tags = {
  }
  vcn_id = oci_core_vcn.default-vcn.id
}

resource oci_core_default_dhcp_options default-DHCP-Options-for-default-vcn {
  compartment_id = data.bitwarden_secret.tenancy_ocid.value
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ganeshbhambarkar@gmail.com"
    "Oracle-Tags.CreatedOn" = "2025-02-16T09:30:18.782Z"
  }
  display_name     = "Default DHCP Options for default-vcn"
  domain_name_type = "CUSTOM_DOMAIN"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.default-vcn.default_dhcp_options_id
  options {
    custom_dns_servers = [
    ]
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    search_domain_names = [
      "vcn02161030.oraclevcn.com",
    ]
    type = "SearchDomain"
  }
}

resource oci_core_default_security_list export_Default-Security-List-for-default-vcn {
  compartment_id = data.bitwarden_secret.tenancy_ocid.value
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ganeshbhambarkar@gmail.com"
    "Oracle-Tags.CreatedOn" = "2025-02-16T09:30:18.782Z"
  }
  display_name = "Default Security List for default-vcn"
  egress_security_rules {
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    protocol  = "all"
    stateless = "false"
  }
  freeform_tags = {
  }
  ingress_security_rules {
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
  }
  ingress_security_rules {
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
  }
  ingress_security_rules {
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "80"
      min = "80"
    }
  }
  ingress_security_rules {
    description = "SSH"
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
    }
  }
  ingress_security_rules {
    description = "HTTPS"
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "443"
      min = "443"
    }
  }
  ingress_security_rules {
    description = "Wireguard"
    protocol    = "17"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    udp_options {
      max = "51820"
      min = "51820"
    }
  }
  manage_default_resource_id = oci_core_vcn.default-vcn.default_security_list_id
}

resource oci_core_default_route_table export_Default-Route-Table-for-default-vcn {
  compartment_id = data.bitwarden_secret.tenancy_ocid.value
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ganeshbhambarkar@gmail.com"
    "Oracle-Tags.CreatedOn" = "2025-02-16T09:30:18.782Z"
  }
  display_name = "Default Route Table for default-vcn"
  freeform_tags = {
  }
  manage_default_resource_id = oci_core_vcn.default-vcn.default_route_table_id
  route_rules {
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.export_Internet-Gateway-default-vcn.id
    route_type        = "STATIC"
  }
}

resource oci_core_instance_maintenance_event export_instance_maintenance_event {
  defined_tags = {
  }
  freeform_tags = {
  }
  instance_maintenance_event_id = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  time_window_start             = "2025-03-29T23:42:20Z"

  lifecycle {
    ignore_changes = [instance_maintenance_event_id]
  }
}
