name: ssh-attackers
filters:
 - Alert.Remediation == true && Alert.GetScope() == "Ip" && lower(Alert.GetScenario() ?? "") contains "ssh"
decisions:
 - type: ban
   duration: 240h
on_success: break
---
name: cve-scanners
filters:
 - Alert.Remediation == true && Alert.GetScope() == "Ip" && lower(Alert.GetScenario() ?? "") contains "cve"
decisions:
 - type: ban
   duration: 480h
on_success: break
---
name: my_countries
filters:
 - Alert.Remediation == true && Alert.GetScope() == "Ip" && Alert.Source.Cn in ['IN', 'DE']
decisions:
 - type: ban
   duration: 4h
on_success: break
---
name: default_remediation
filters:
 - Alert.Remediation == true && Alert.GetScope() in ["Ip", "Range"]
decisions:
 - type: ban
   duration: 24h
on_success: break
