name: crowdsecurity/immich-whitelists
description: "Whitelist false positive from Immich-api"
filter: "evt.Meta.service == 'http' && evt.Meta.log_type in ['http_access-log', 'http_error-log']"
whitelist:
  reason: "Whitelist false positive from Immich-api"
  expression:
   - evt.Parsed.traefik_router_name contains 'immich' && evt.Meta.http_verb == 'GET' && (evt.Meta.http_status == '200' || evt.Meta.http_status == '206') && (evt.Parsed.request matches '/api/assets' || evt.Parsed.request matches '/api/albums' || evt.Parsed.request matches '/api/timeline/bucket')
   - evt.Parsed.traefik_router_name contains 'immich' && evt.Meta.http_verb == 'GET' && (evt.Meta.http_status == '400' || evt.Meta.http_status == '404') && evt.Parsed.request matches '/api/assets.*thumbnail' # bug in the app where it has assets in the timeline even after they're deleted
   - evt.Parsed.traefik_router_name contains 'immich' && evt.Meta.http_verb == 'GET' && evt.Meta.http_status == '304' && (evt.Parsed.request matches '/api')
