---
- name: Install bitwarden CLI
  hosts: localhost
  gather_facts: false
  environment:
    PATH: "~/.local/bin:{{ lookup('env', 'PATH') }}"
  tasks:
    - name: Collect only facts returned by facter
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - '!min'
          - architecture
          - os_family

    - name: Set bitwarden CLI architecture
      ansible.builtin.set_fact:
        bws_architecture: >-
          {%- set arch_map = {'arm64': 'aarch64'} -%}
          {{ arch_map.get(ansible_architecture, ansible_architecture) }}

    - name: Set bitwarden CLI OS family
      ansible.builtin.set_fact:
        bws_os_family: >-
          {%- set os_map = {'Darwin': 'apple-darwin'} -%}
          {{ os_map.get(ansible_os_family, 'unknown-linux-gnu') }}

    - name: Print a message
      ansible.builtin.debug:
        msg: "{{ bws_architecture }} {{ bws_os_family }}"

    - name: Create local bin directory
      ansible.builtin.file:
        path: ~/.local/bin
        state: directory
        mode: '0755'

    - name: Download Bitwarden Secrets CLI and unzip
      ansible.builtin.unarchive:
        src: "https://github.com/bitwarden/sdk-sm/releases/download/bws-v1.0.0/bws-{{ bws_architecture }}-{{ bws_os_family }}-1.0.0.zip"
        dest: ~/.local/bin
        remote_src: true
