global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v2
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  static_configs:
  - targets:
    - localhost:9090
- job_name: traefik
  static_configs:
    - targets: ['host.docker.internal:80']
- job_name: node
  static_configs:
    - targets: ['host.docker.internal:9100']
- job_name: crowdsec
  scheme: http
  static_configs:
    - targets: ['crowdsec:6060']
- job_name: docker
  static_configs:
    - targets: ["host.docker.internal:9323"]
- job_name: cadvisor
  static_configs:
    - targets: ['cadvisor:8080']
- job_name: 'crowdsec-firewall-bouncer'
  static_configs:
    - targets: ['host.docker.internal:9034']
- job_name: gatus
  static_configs:
    - targets: ['gatus:8080']