apiVersion: 1
contactPoints:
    - orgId: 1
      name: Telegram
      receivers:
        - uid: dekudqptsb280f
          type: telegram
          settings:
            bottoken: $TELEGRAM_BOT_TOKEN
            chatid: |
              $TELEGRAM_CHAT_ID
            disable_notification: false
            disable_web_page_preview: false
            protect_content: true
          disableResolveMessage: false