{
 "title": "Main Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disk usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - avg(node_filesystem_free_bytes{mountpoint=\"/\"}) / avg(node_filesystem_size_bytes{mountpoint=\"/\"})",
     "legendFormat": "${metric} (average)"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg(node_memory_MemAvailable_bytes)/ avg(node_memory_MemTotal_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg without (mode,cpu,instance,job) (\n  1 - rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container memory usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(container_label_com_docker_compose_service) (container_memory_rss{name=~\".+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container memory limit usage percentage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(container_label_com_docker_compose_service) (container_memory_rss{name=~\".+\"}/(container_spec_memory_limit_bytes{name=~\".+\"} > 0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container (excluding traefik)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_network_transmit_bytes_total{name!~\"node_exporter||cadvisor|traefik|wireguard\"}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container (excluding traefik)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_network_receive_bytes_total{name!~\"node_exporter||cadvisor|traefik|wireguard\"}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Services down according to gatus",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(clamp(gatus_results_endpoint_success,0, 1)) - sum(clamp(gatus_results_endpoint_success,0, 1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Services down according to gatus",
   "type": "table",
   "gridPos": { "h": 7, "w": 13, "x": 4, "y": 29 },
   "targets": [
    {
     "expr": "avg(gatus_results_endpoint_success == 0) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Traefik", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum(increase(traefik_entrypoint_requests_total[$__rate_interval]))",
     "legendFormat": "Request count"
    }
   ]
  },
  {
   "title": "Unauthorized/forbidden responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "sum(increase(traefik_entrypoint_requests_total{code=~\"403|401\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non-TLS successes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A-$B", "type": "math" }
   ]
  },
  {
   "title": "Total data transferred since restart",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_requests_bytes_total) + sum(traefik_entrypoint_responses_bytes_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traefik data transfer rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_bytes_total[$__rate_interval]) +rate(traefik_entrypoint_responses_bytes_total[$__rate_interval]))",
     "legendFormat": "Traefik data transfer rate"
    }
   ]
  }
 ]
}